config/routes.rb
Rails.application.routes.draw do
  resources :investor_contents
  resources :post_banners
  resources :investors
  resources :brand_banners
  resources :new_investments
  resources :sector_banners
  resources :group_banners
  resources :banners
  resources :contents
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :social_media
  devise_for :users
  resources :posts
  resources :brands
  resources :sectors
  resources :homes

  root 'pages#welcome'

  get 'pages/group' => 'pages#group', :path => 'group'

  get 'pages/contact' => 'pages#contact', :path => 'contact'

  get 'new_investment_page' => 'new_investments#index', :path => 'new-investment'

  get 'investors_page' => 'investors#index', :path => 'investors'

  # get 'pages/investor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :brands

  has_attached_file :sector_photo, styles: { big: "1920x800<", thumb: "275x135#" },
    default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :sector_photo,
    content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end

end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show, :index]

  # GET /sectors
  # GET /sectors.json
  def index
    @sectors = Sector.order("order" => "asc").all

    @banners = SectorBanner.order("id" => "desc").all

    @new_investment = NewInvestment.first
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    @brands = Brand.all
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to @sector, notice: 'Sector was successfully created.' }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to @sector, notice: 'Sector was successfully updated.' }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name, :description, :sector_photo)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.slim
.container-fluid
  = form_for @sector do |f|
    - if @sector.errors.any?
      #error_explanation
        h2 = "#{pluralize(@sector.errors.count, "error")} prohibited this sector from being saved:"
        ul
          - @sector.errors.full_messages.each do |message|
            li = message

    .field
      = f.label :name
      = f.text_field :name, :class => 'form-control'
    .field
      = f.label :description
      = f.text_area :description, :class => 'form-control'
    .field
      = f.label :sector_photo
      = f.file_field :sector_photo

    .actions = f.submit "Create Sector", :class => 'btn btn-default'

app/views/sectors/_sectors_partial.slim
=link_to sector do
  .row
    .col-md-3.col-ms-3
      .sector-image
        .styled-div style='background-image: url("#{sector.sector_photo(:thumb)}");'
          h3.sector-name = sector.name
    .col-md-9.col-ms-9
      p =( truncate sanitize(sector.description), length: 160 ) unless sector.description.nil?
end

app/views/sectors/edit.html.slim
h1 Editing sector

== render 'form'

= link_to 'Show', @sector
'|
= link_to 'Back', sectors_path

app/views/sectors/index.html.slim
.banner

  .banner-body
    - @banners.each do |banner|
      .banner-content style='background-image: url("#{banner.photo(:big)}");'

  .logo-information
    .col-md-10.slider_leftpart

      .col-md-3.text-left

      .col-md-9.text-left

        - @banners.each do |banner|

          .banner-description.hide
            h2 =banner.title.html_safe unless banner.nil?
            p =banner.description.html_safe unless banner.nil?

    .col-md-2.text-left

  .arrow
    .arrow-click
      .arrow-in

.container-fluid.sectors
  h1 We have companies in 8 different sectors
  
  .container

    .col-md-12.visible-md-block.visible-lg-block
      -@sectors.each_with_index do |sector, i|
        
        - if((i) % 2 == 0)
          =link_to sector do
              .row
                .col-md-3.col-ms-3
                  .sector-image
                    .styled-div style='background-image: url("#{sector.sector_photo(:thumb)}");'
                      h3.sector-name = sector.name
                .col-md-9.col-ms-9
                  p =sanitize(sector.description, :tags=>[]).truncate(240, :separator => " ").html_safe
          end

        - else
          =link_to sector do
              .row
                .col-md-9.col-ms-9
                  p =sanitize(sector.description, :tags=>[]).truncate(240, :separator => " ").html_safe
                .col-md-3.col-ms-3
                  .sector-image
                    .styled-div style='background-image: url("#{sector.sector_photo(:thumb)}");'
                      h3.sector-name =sector.name
          end

      =link_to new_investment_page_path do
          .row
            .col-md-3.col-ms-3
              .sector-image
                .styled-div style='background-image: url("#{@new_investment.photo(:thumb)}");'
                  h3.sector-name = @new_investment.title
            .col-md-9.col-ms-9
              p =sanitize(@new_investment.description, :tags=>[]).truncate(240, :separator => " ").html_safe
      end

    .col-md-12.visible-sm-block.visible-xs-block
      -@sectors.each_with_index do |sector, i|
        
        =link_to sector do
            .row
              .col-md-3.col-ms-3
                .sector-image
                  .styled-div style='background-image: url("#{sector.sector_photo(:thumb)}");'
                    h3.sector-name = sector.name
              .col-md-9.col-ms-9
                p =sanitize(sector.description, :tags=>[]).truncate(240, :separator => " ").html_safe
        end

      =link_to new_investment_page_path do
          .row
            .col-md-3.col-ms-3
              .sector-image
                .styled-div style='background-image: url("#{@new_investment.photo(:thumb)}");'
                  h3.sector-name = @new_investment.title
            .col-md-9.col-ms-9
              p =sanitize(@new_investment.description, :tags=>[]).truncate(240, :separator => " ").html_safe
      end

app/views/sectors/new.html.slim
h1 New sector

== render 'form'

= link_to 'Back', sectors_path

app/views/sectors/show.html.slim
.banner-sector
  .banner-sector-body
    .banner-sector-content style='background-image: url("#{@sector.sector_photo.url(:big)}");'
      h2 = @sector.name

      .arrow
        .arrow-click
          .arrow-in

.container-fluid
  p#notice = notice

.container.description.col-md-8.col-md-offset-2
  = @sector.description.html_safe

.container.col-md-8.col-md-offset-2.list-brands-by-sector
  - Brand.all.where(sector_id: [params[:id]]).each do |var|
    .col-md-4 = link_to image_tag(var.logo_for_brand.url(:thumb), class:'brand-logo-thumb'), brand_path(var)
.container-fluid
- if current_user.try(:admin?)
  = link_to 'Edit', edit_sector_path(@sector), class: 'btn btn-danger'
  = link_to 'Back', sectors_path, class: 'btn btn-default'