config/routes.rb
Rails.application.routes.draw do
  resources :investor_contents
  resources :post_banners
  resources :investors
  resources :brand_banners
  resources :new_investments
  resources :sector_banners
  resources :group_banners
  resources :banners
  resources :contents
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :social_media
  devise_for :users
  resources :posts
  resources :brands
  resources :sectors
  resources :homes

  root 'pages#welcome'

  get 'pages/group' => 'pages#group', :path => 'group'

  get 'pages/contact' => 'pages#contact', :path => 'contact'

  get 'new_investment_page' => 'new_investments#index', :path => 'new-investment'

  get 'investors_page' => 'investors#index', :path => 'investors'

  # get 'pages/investor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :sector
  belongs_to :new_investment

# Brand Photo File Uploads
  has_attached_file :brand_photo,
    styles: { big: "1920x800<"},
    default_url: "/images/:style/missing.png",
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :brand_photo,
    content_type: /\Aimage\/.*\Z/

  # Brand Logo File Uploads
  has_attached_file :logo_for_brand,
    styles: { thumb: "200x150>", medium: "400x300>" },
    default_url: "/images/:style/missing.png",
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :logo_for_brand,
    content_type: /\Aimage\/.*\Z/

    def s3_credentials
      {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show, :index]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    @banners = BrandBanner.order("id" => "desc").all
    
    @sector = Sector.find_by(params[:id])

    @sectors = Sector.order("order" => "asc").all
  end


  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :url, :description, :brand_photo, :logo_for_brand, :sector_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.slim
.container-fluid
  = form_for @brand do |f|
    - if @brand.errors.any?
      #error_explanation
        h2 = "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
        ul
          - @brand.errors.full_messages.each do |message|
            li = message

    .field
      = f.label :name
      = f.text_field :name, :class => 'form-control'
    .field
      = f.label :url
      = f.text_field :url, :class => 'form-control'
    .field
      = f.label :description
      = f.text_area :description, :class => 'form-control'
    .field
      = f.label :sector_id
      = f.select(:sector_id, Sector.all.collect {|s| [ s.name, s.id] }, {include_blank: true})
    .field
      = f.label :brand_photo
      = f.file_field :brand_photo
    .field
      = f.label :logo_for_brand
      = f.file_field :logo_for_brand
    .actions = f.submit 'Create Brand', :class => 'btn btn-default'

app/views/brands/edit.html.slim
h1 Editing brand

== render 'form'

= link_to 'Show', @brand
'|
= link_to 'Back', brands_path

app/views/brands/index.html.slim
.banner.brand-banner

  .banner-body
    - @banners.each do |banner|
      .banner-content style='background-image: url("#{banner.photo(:big)}");'

  .logo-information
    .col-md-10.slider_leftpart

      .col-md-3.text-left

      .col-md-9.text-left

        - @banners.each do |banner|

          .banner-description.hide
            h2 =banner.title.html_safe unless banner.nil?
            p =banner.description.html_safe unless banner.nil?

    .col-md-2.text-left

.list-unstyled.brand-tabs#brand_courssel
  - @sectors.each do |sector|
    .col-8
      a data-toggle="pill" href="#temp_#{sector.id}" style='background-image: url("#{sector.sector_photo(:big)}");'
        span =sector.name
  
.container
  .tab-content.col-md-12
    - @sectors.each do |sector|
      div id="#temp_#{sector.id}" class="tab-pane brand-tab"
        - Brand.all.where(sector_id: sector.id).each do |var|
          .col-md-4 = link_to image_tag(var.logo_for_brand.url(:thumb), class:'brand-logo-thumb'), brand_path(var)
  br
  br
  br

app/views/brands/new.html.slim
h1.text-center New brand

== render 'form'

= link_to 'Back', brands_path

app/views/brands/show.html.slim
.banner-sector
  .banner-sector-body
    .banner-sector-content style='background-image: url("#{@brand.brand_photo.url(:big)}");'
      h2 = @brand.name

      .arrow
        .arrow-click
          .arrow-in

.brand-photo-overlay

.fadeInBlock.container-fluid
  p#notice = notice
  .text-center
    = link_to @brand.url do
      = image_tag @brand.logo_for_brand.url(:thumb), :target => "_blank", :class=> 'brand-logo-thumb'
    h4 = @brand.sector.name

  .description.container-fluid.col-md-8.col-md-offset-2.text-justify = @brand.description.html_safe

  .container-fluid
  = button_to 'Learn More', @brand.url, :target => "_blank", :class=> 'btn btn-default btn-lg brand-show'

  .container-fluid
  - if current_user.try(:admin?)
    = link_to 'Edit', edit_brand_path(@brand)
    '|
    = link_to 'Back', brands_path