config/routes.rb
Rails.application.routes.draw do
  resources :investor_contents
  resources :post_banners
  resources :investors
  resources :brand_banners
  resources :new_investments
  resources :sector_banners
  resources :group_banners
  resources :banners
  resources :contents
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :social_media
  devise_for :users
  resources :posts
  resources :brands
  resources :sectors
  resources :homes

  root 'pages#welcome'

  get 'pages/group' => 'pages#group', :path => 'group'

  get 'pages/contact' => 'pages#contact', :path => 'contact'

  get 'new_investment_page' => 'new_investments#index', :path => 'new-investment'

  get 'investors_page' => 'investors#index', :path => 'investors'

  # get 'pages/investor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/banner.rb
class Banner < ApplicationRecord
  belongs_to :sector

  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :sector
  belongs_to :new_investment

# Brand Photo File Uploads
  has_attached_file :brand_photo,
    styles: { big: "1920x800<"},
    default_url: "/images/:style/missing.png",
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :brand_photo,
    content_type: /\Aimage\/.*\Z/

  # Brand Logo File Uploads
  has_attached_file :logo_for_brand,
    styles: { thumb: "200x150>", medium: "400x300>" },
    default_url: "/images/:style/missing.png",
    :storage => :s3,
    :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :logo_for_brand,
    content_type: /\Aimage\/.*\Z/

    def s3_credentials
      {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
    end
end

app/models/brand_banner.rb
class BrandBanner < ApplicationRecord
  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/executive.rb
class Executive < ApplicationRecord
  belongs_to :group

  has_attached_file :photo, styles: { thumb: "150x150#" },
    default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :executives
  has_attached_file :photo, styles: { big: "1920x800<", thumb: "150x150#" },
    default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end

  def self.executive_committee

    return false if first.nil?

    first.executives.where(position: 'Executive Committee')
  end

  def self.board_of_directors
    return false if first.nil?
    
    first.executives.where(position: 'Board of Directors')
  end

end

app/models/group_banner.rb
class GroupBanner < ApplicationRecord

  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/investor.rb
class Investor < ApplicationRecord
  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
end

app/models/post_banner.rb
class PostBanner < ApplicationRecord
  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :brands

  has_attached_file :sector_photo, styles: { big: "1920x800<", thumb: "275x135#" },
    default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials}
  validates_attachment_content_type :sector_photo,
    content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end

end

app/models/sector_banner.rb
class SectorBanner < ApplicationRecord
  has_attached_file :photo, styles: { big: "1920x800<", thumb: "275x135#" }, default_url: "/images/:style/missing.jpg", :storage => :s3, :s3_credentials => Proc.new{|a| a.instance.s3_credentials} 
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  def s3_credentials
    {:bucket => ENV['s3_bucket'], :access_key_id => ENV['aws_access_key_id'], :secret_access_key => ENV['aws_access_secret']}
  end
end

app/models/social_medium.rb
class SocialMedium < ApplicationRecord
  belongs_to :brand
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contact_us/contacts/new.html.erb
<div class="contact_back">
  <div class="container contact-form">
    <div class="col-md-8 col-md-offset-2">
      <h1><%= t('.contact_us') %></h1>
        <%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
          <% if ContactUs.require_name %>
            <div class='string required' id='contact_us_contact_name_input'>
              
              <%= f.text_field :name, :class => 'form-control', :placeholder => t('.name') + '*' %>
              <% if f.object.errors[:name].present? %>
                <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
              <% end %>
            </div>
          <% end %>
          <div class='string required' id='contact_us_contact_email_input'>
            
            <%= f.text_field :email, :class => 'form-control', :placeholder => t('.email') + '*' %>
            <% if f.object.errors[:email].present? %>
              <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
            <% end %>
          </div>
          <% if ContactUs.require_subject %>
            <div class='string required' id='contact_us_contact_subject_input'>
              <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
              <%= f.text_field :subject %>
              <% if f.object.errors[:subject].present? %>
                <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
              <% end %>
            </div>
          <% end %>
          <div class='text required' id='contact_us_contact_message_input'>
            <%= f.text_area :message, :class => 'form-control', :placeholder => t('.message') + '*' %>
            <% if f.object.errors[:message].present? %>
              <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
            <% end %>
          </div>
          <div class='commit'>
            <%= f.submit :submit, :class => 'submit create btn btn-default', :title => t('.submit') %>
          </div>
        <% end %>
      </div>
  </div>
</div>

<!--
<div class="container text-center contact-countries">
  <hr>
  <div class="col-md-3">
    <h4>USA</h4>
    <p>
      12345 Main St.
      Miami, FL 33190
    </p>
  </div>
  <div class="col-md-3">
    <h4>Latin America</h4>
    <p>
      12345 Main St.
      Miami, FL 33190
    </p>
  </div>
  <div class="col-md-3">
    <h4>Europe</h4>
    <p>
      12345 Main St.
      Miami, FL 33190
    </p>
  </div>
  <div class="col-md-3">
    <h4>Middle East</h4>
    <p>
      12345 Main St.
      Miami, FL 33190
    </p>
  </div>
</div>
-->

app/views/layouts/_footer.html.slim
footer#footer

  .footer1
    .container
      .row
        .col-md-2 &nbsp;
        .col-md-8
          .col-md-4.col-sm-4.widget
            h3.widget-title
            .widget-body
              ul.footer_menu
                li = link_to 'GROUP', pages_group_path
                li = link_to 'SECTORS', sectors_path
                li = link_to 'BRANDS', brands_path
                li = link_to 'NEWS', posts_path
                li = link_to 'CONTACT US', contact_us_path
                li = link_to 'LEGAL TERMS', "#"
                li = link_to 'LOGIN', admin_root_path, :class => "highlight-green"

          .col-md-4.col-sm-4.widget
            h3.widget-title
            .widget-body
              .footer_address
                strong USA
                p 123 Main St. Miami, FL 33190

                strong Latin America
                p 123 Main St. Miami, FL 33190

                strong Europe
                p 123 Main St. Miami, FL 33190

                strong Middle East
                p 123 Main St. Miami, FL 33190


          .col-md-3.col-sm-4.widget
            h3.widget-title
            .widget-body
              .follow-me-icons.text-right

                = link_to "https://twitter.com/VanDutchStyle"
                  i.fa.fa-twitter.fa-2
                = link_to "https://plus.google.com/+VandutchStyle"
                  i.fa.fa-google-plus.fa-2
                = link_to "#"
                  i.fa.fa-linkedin-square.fa-2
                = link_to "https://www.facebook.com/VanDutchGroup"
                  i.fa.fa-facebook.fa-2

              .flag_icon_area
                = link_to "#" do
                  = image_tag "templates/flag_icon.png", :class => "img-responsive"
                end

              p.copyright.text-right &copy; LBDR Group 2016


        .col-md-2 &nbsp;

app/views/layouts/_header.html.slim
nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation"
  = link_to image_tag('lbdr.svg'), root_path, :class=>"sidebar-logo"

  ul.nav.navmenu-nav
    li = link_to 'Group', pages_group_path
    li = link_to 'Sectors', sectors_path
    li = link_to 'Brands', brands_path
    li = link_to 'Investors', investors_page_path
    li = link_to 'New investments', new_investment_page_path
    li = link_to 'News', posts_path
    li = link_to 'Contact', contact_us_path

  .follow-me-icons.header_social
    .social-icons-content
      = link_to '<i class="fa fa-twitter fa-2"></i>'.html_safe, 'https://twitter.com/VanDutchStyle'
      = link_to '<i class="fa fa-google-plus fa-2"></i>'.html_safe, 'https://plus.google.com/+VandutchStyle'
      = link_to '<i class="fa fa-linkedin-square fa-2"></i>'.html_safe, '#'
      = link_to '<i class="fa fa-facebook fa-2"></i>'.html_safe, 'https://www.facebook.com/VanDutchGroup'

div class=(current_page?("/") ? 'navbar navbar-default navbar-fixed-top nav-absolute' : 'navbar navbar-default navbar-fixed-top')
  
  button id="nav-icon1" class=(current_page?("/") ? 'nav-home' : 'nav-in') type="button" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body"
    span
    span
    span

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LBDR Group</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Alegreya+Sans:300,500|Alegreya+Sans+SC:300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
    <!-- Add the slick-theme.css if you want default styling -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    
    <%= javascript_include_tag 'jquery.simulate'%>

    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.3.6/slick.min.js"/></script>
    
    <!-- 3 KB -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> <!-- 16 KB -->
    
    <!-- fotorama.css & fotorama.js. -->
    <link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet"> 
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/dashboard.html.slim
.container-fluid
  h1 Admin Dashboard

  = link_to 'Create a Blog Post', new_post_path
  = link_to 'Add Brand', new_brand_path
  = link_to 'Add Sector', new_sector_path

app/views/pages/group.html.slim
.banner

  .banner-body
    - @banners.each do |banner|
      .banner-content style='background-image: url("#{banner.photo(:big)}");'

  .logo-information
    .col-md-10.slider_leftpart

      .col-md-3.text-left

      .col-md-9.text-left

        - @banners.each do |banner|

          .banner-description.hide
            h2 =banner.title.html_safe unless banner.nil?
            p =banner.description.html_safe unless banner.nil?

    .col-md-2.text-left

  .arrow
    .arrow-click
      .arrow-in

.container.section
  .group-info

    .triangle

    ul#tabs.nav data-tabs="pills"
      li
        a data-toggle="pill" href="#model"  Model
      li.active
        a data-toggle="pill" href="#about" About
      li
        a data-toggle="pill" href="#spirit"  Spirit


    #my-tab-content.tab-content.col-md-8.col-md-offset-2
      #model.tab-pane
        p =@group.model.html_safe unless @group.nil?
      #about.tab-pane.active
        p =@group.about.html_safe unless @group.nil?
      #spirit.tab-pane
        p =@group.spirit.html_safe unless @group.nil?

.governance-section
  .container
    .pills-center
      ul#tabs.nav data-tabs="pills"
        li.active
          a data-toggle="pill" href="#executive_committee" id="executive-committee"  
            span Executive Committee
            span.arrow_board >>
        li
          a data-toggle="pill" href="#board_of_directors"  
            span Board of Directors 
            span.arrow_board >>


      #my-tab-content.tab-content
        #executive_committee.tab-pane.fade.in.active
          .governance-description.col-md-8.col-md-offset-2
            =@group.executive_committee_description.html_safe unless @group.nil?

          .row
            .col-md-12
              - @executive_committee.each do |exec|
                .people.col-md-3
                  .group-image style='background-image: url("#{exec.photo(:thumb)}")'
                  h4 = "#{exec.first_name} #{exec.last_name}"
                  p =exec.position

        #board_of_directors.tab-pane.fade
          .governance-description.col-md-8.col-md-offset-2
            =@group.board_of_directors_description.html_safe unless @group.nil?
          
          .row
            .col-md-12
              - @board_of_directors.each do |board|
                .people.col-md-3
                  .group-image style='background-image: url("#{board.photo(:thumb)}")'
                  h4 ="#{board.first_name} #{board.last_name}"
                  p =board.position

app/views/pages/investor.html.slim
h1 Pages#investor
p Find me in app/views/pages/investor.html.slim

app/views/pages/welcome.html.slim
.banner

  .banner-body
    - @banners.each do |banner|

      - unless banner.sector.nil?
        .banner-content style='background-image: url("#{banner.sector.sector_photo(:big)}");'
      - else
        .banner-content style='background-image: url("#{banner.photo(:big)}");'


  .logo-information
    .col-md-10.slider_leftpart

      .col-md-3.text-left

      .col-md-9.text-left

        .logo_lbdr =image_tag('lbdr.svg')

        - @banners.each do |banner|

          .banner-description.hide
            h2 =@banners[0].title.html_safe unless @banners[0].nil?
            p =@banners[0].description.html_safe unless @banners[0].nil?

    .col-md-2.text-left

  .arrow
    .arrow-click
      .arrow-in

  #menu-wrapper
    ul.nav
      li.cell
        i.fa.fa-home.fa-2
        span Home

      li.cell
        i.fa.fa-anchor.fa-2
        span link-to="#{'/sectors/' + @banners[1].sector.id.to_s}" Marine

      li.cell
        i.fa.fa-car.fa-2
        span link-to="#{'/sectors/' + @banners[2].sector.id.to_s}" Automotive

      li.cell
        i.fa.fa-paper-plane.fa-2
        span link-to="#{'/sectors/' + @banners[3].sector.id.to_s}" Aviation

      li.cell
        i.fa.fa-coffee.fa-2
        span link-to="#{'/sectors/' + @banners[4].sector.id.to_s}" Real Estate

      li.cell
        i.fa.fa-child.fa-2
        span link-to="#{'/sectors/' + @banners[5].sector.id.to_s}" Entertaintment and Leisure

      li.cell
        i.fa.fa-star.fa-2
        span link-to="#{'/sectors/' + @banners[6].sector.id.to_s}" Fasion And Accesories

      li.cell
        i.fa.fa-video-camera.fa-2
        span link-to="#{'/sectors/' + @banners[7].sector.id.to_s}" Media

      li.cell
        i.fa.fa-wifi.fa-2
        span link-to="#{'/sectors/' + @banners[8].sector.id.to_s}" Technology
      

section.section_area.with_padding


    .container.text-center
      h3.boldtext =@content[0].title.html_safe unless @content[0].nil?
      p.text-muted
        =@content[0].description.html_safe unless @content[0].nil?

.col-md-12
  .gallery_menu.row
    - @sectors.each_with_index do |sector, i|
      .col-md-3.col-sm-6.sector_thumb.no-padding

        = link_to "#{sector_path(sector)}" do
          = image_tag "#{sector.sector_photo.url(:original)}", :class => "img-responsive", :alt => sector.name
          .carousel-caption.mylink.twoline
            h3 =sector.name
        end


      - if((i + 1) % 4 == 0)
        .clear_fix_site

section.section_area.with_padding


    .container.text-center
      h3.boldtext =@content[1].title.html_safe unless @content[1].nil?
      =@content[1].description.html_safe unless @content[1].nil?